services:
  emotion-classification-audio:
    image: some.registry.com/xr2learn-enablers/ed-classification-audio:latest
    build:
      context: 'Emotion_Classification/Emotion_Classification_Audio_Modality'
      dockerfile: 'Dockerfile'
    volumes:
      - "./Emotion_Classification/Emotion_Classification_Audio_Modality:/app"
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
    working_dir: /app
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
    command: python emotion_classification_audio_modality/predict.py
  
  emotion-classification-bm:
    image: some.registry.com/xr2learn-enablers/ed-classification-bm:latest
    build:
      context: 'Emotion_Classification/Emotion_Classification_BM_Modality'
      dockerfile: 'Dockerfile'
    volumes:
      - "./Emotion_Classification/Emotion_Classification_BM_Modality:/app"
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
    working_dir: /app
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
      - REDIS_HOST=redis
    command: python emotion_classification_bm_modality/predict.py
    depends_on:
      - redis

  emotion-classification-body-tracking:
    image: some.registry.com/xr2learn-enablers/emotion-classification-body-tracking:latest
    build:
      context: 'Emotion_Classification/Emotion_Classification_Body_Tracking_Modality'
      dockerfile: 'Dockerfile'
    volumes:
      - "./Emotion_Classification/Emotion_Classification_Body_Tracking_Modality:/app"
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
    working_dir: /app
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
      - REDIS_HOST=redis
    command: python emotion_classification_body_tracking_modality/predict.py
    depends_on:
      - redis

  fusion-layer:
    image: some.registry.com/xr2learn-enablers/fusion-layer:latest
    build:
      context: 'Multimodal_Fusion/Multimodal_Fusion_Layer'
      dockerfile: 'Dockerfile'
    volumes:
      - "./Multimodal_Fusion/Multimodal_Fusion_Layer:/app"
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
    working_dir: /app
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
      - REDIS_HOST=redis
    command: python multimodal_fusion_layer/predict.py
    depends_on:
      - redis

  ed-evaluation:
    image: some.registry.com/xr2learn-enablers/ed-evaluation:latest
    build:
      context: 'ED_Evaluation/ED_Evaluation'
      dockerfile: 'Dockerfile'
    volumes:
      - "./ED_Evaluation/ED_Evaluation:/app"
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
    working_dir: /app
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
    command: python ed_evaluation/evaluate.py

  redis:
    image: redis:7.2.2
    ports:
      - "6379:6379"

  personalization-tool:
    image: some.registry.com/xr2learn-enablers/personalization-tool:latest
    working_dir: /app
    environment:
      - REDIS_HOST=redis
    command: python personalization_tool/suggest_activity_level.py
    depends_on:
      - redis

  dashboard:
    image: some.registry.com/xr2learn-enablers/dashboard:latest
    working_dir: /app
    environment:
      - REDIS_HOST=redis
    command: python web_app.py
    depends_on:
      - redis
      - personalization-tool
    ports:
      - "8000:8000"

  inference-data-processing-bm:
    image: some.registry.com/xr2learn-enablers/inference-data-processing-bm:latest
    build:
      context: 'Inference_Data_Processing/Inference_Data_Processing_BM_Modality'
      dockerfile: 'Dockerfile'
    volumes:
      - "./Inference_Data_Processing/Inference_Data_Processing_BM_Modality:/app"
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
    working_dir: /app
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
      - REDIS_HOST=redis
    command: python inference_data_processing_bm_modality/process_data.py
    depends_on:
      - redis
    
  inference-data-processing-body-tracking:
    image: some.registry.com/xr2learn-enablers/inference-data-processing-body-tracking:latest
    build:
      context: 'Inference_Data_Processing/Inference_Data_Processing_Body_Tracking_Modality'
      dockerfile: 'Dockerfile'
    volumes:
      - "./Inference_Data_Processing/Inference_Data_Processing_Body_Tracking_Modality:/app"
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
    working_dir: /app
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
      - REDIS_HOST=redis
    command: python inference_data_processing_body_tracking_modality/process_data.py
    depends_on:
      - redis

  mock-xroom-writer:
    image: some.registry.com/xr2learn-enablers/mock-xroom-writer:latest
    build:
      context: 'Mock_XRoom_Writer/Mock_XRoom_Writer_BM_BT_Modality'
      dockerfile: 'Dockerfile'
    volumes:
      - "./datasets/:/app/datasets"
      - "./outputs:/app/outputs"
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
    working_dir: /app
    command: python mock_xroom_writer_bm_bt_modality/mock_xroom_writer.py
