version: '3'
services:
  emotion-classification-audio:
    image: some.registry.com/xr2learn-enablers/ed-classification-audio:latest
    build:
      context: 'Emotion_Classification/Emotion_Classification_Audio_Modality'
      dockerfile: 'Dockerfile'
    volumes:
      - "./Emotion_Classification/Emotion_Classification_Audio_Modality:/app"
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
    working_dir: /app
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
    command: python emotion_classification_audio_modality/predict.py

  fusion-layer:
    image: some.registry.com/xr2learn-enablers/fusion-layer:latest
    build:
      context: 'Multimodal_Fusion/Multimodal_Fusion_Layer'
      dockerfile: 'Dockerfile'
    volumes:
      - "./Multimodal_Fusion/Multimodal_Fusion_Layer:/app"
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
    working_dir: /app
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
      - REDIS_HOST=redis
    command: python multimodal_fusion_layer/predict.py
    depends_on:
      - redis

  ed-evaluation:
    image: some.registry.com/xr2learn-enablers/ed-evaluation:latest
    build:
      context: 'ED_Evaluation/ED_Evaluation'
      dockerfile: 'Dockerfile'
    volumes:
      - "./ED_Evaluation/ED_Evaluation:/app"
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
    working_dir: /app
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
    command: python ed_evaluation/evaluate.py

  redis:
    image: redis:7.2.2
    ports:
      - "6379:6379"

  personalisation-tool:
    image: some.registry.com/xr2learn-enablers/personalisation-tool:latest
    working_dir: /app
    environment:
      - REDIS_HOST=redis
    command: python personalisation_tool/suggest_activity_level.py
    depends_on:
      - redis

  demo-ui:
    image: some.registry.com/xr2learn-enablers/demo-ui:latest
    working_dir: /app
    environment:
      - REDIS_HOST=redis
    command: python web_app.py
    depends_on:
      - redis
      - personalisation-tool
    ports:
      - "8000:8000"


